#!/bin/tcsh
echo ---TESTING ALPHA---
echo make clean
make clean >& /dev/null
echo make config-alpha
make config-alpha >& /dev/null
echo make 
make > regress.alpha
echo make sim-tests
make sim-tests >>& regress.alpha
echo grep Error regress.alpha
grep Error regress.alpha
echo ---TESTING PISA---
echo make clean
make clean >& /dev/null
echo make config-pisa
make config-pisa >& /dev/null
echo make 
make > regress.pisa
echo make sim-tests
make sim-tests >>& regress.pisa
echo grep Error regress.pisa
grep Error regress.pisa
echo ---TESTING ARM---
echo make clean
make clean >& /dev/null
echo make config-arm
make config-arm >& /dev/null
echo make 
make > regress.arm
echo make sim-tests
make sim-tests >>& regress.arm
echo grep Error regress.arm
grep Error regress.arm
