##===- tools/lli/Makefile ------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL    := ../..
TOOLNAME := lli
LINK_COMPONENTS := jit interpreter native bitreader selectiondag instrumentation bitwriter 
###LINK_COMPONENTS := bitreader bitwriter instrumentation scalaropts ipo

# Enable JIT support
include $(LEVEL)/Makefile.common
